# Generated by Django 5.2.7 on 2025-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default='2005-05-07'),
            preserve_default=False,
        ),
    ]
