# Generated by Django 5.2.7 on 2025-11-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freteiro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
