# Generated by Django 5.2.7 on 2025-11-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_freteiro_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freteiro',
            name='veiculo',
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
