# Generated by Django 5.2.7 on 2025-11-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_freteiro_veiculo_alter_freteiro_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freteiro',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
