# Generated by Django 5.2.7 on 2025-11-09 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_freteiro_cpf_alter_freteiro_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitarFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('largura', models.FloatField()),
                ('altura', models.FloatField()),
                ('valor', models.FloatField()),
                ('endereco_coleta', models.CharField(max_length=200)),
                ('endereco_entrega', models.CharField(max_length=200)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('hora_solicitacao', models.TimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
