# Generated by Django 5.2.7 on 2025-11-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_solicitarfrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitarfrete',
            name='freteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.freteiro'),
        ),
        migrations.AddField(
            model_name='solicitarfrete',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
